# Generated by Django 4.2.3 on 2023-10-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='curso',
            new_name='asignatura',
        ),
    ]
